spring:
  jpa:
    show-sql: false
 
    open-in-view: false
 
my:
  email: ${random.value}@gmail.com
  
logging:
  level:
    org.springframework.security: debug  

appli:
  secretKey: azerty
  validity: 10000
  rememberMe: 10000
    
---
spring:
  profiles:
  - prod
    

  datasource:
    url: jdbc:postgresql://localhost:5434/f_springboot
    username: postgres
    password: postgres
    hikari:
      maximum-pool-size: 10
      connection-timeout: 10000
    
  jpa:
    hibernate:
      ddl-auto: update
      
