server:
  port: 8000
  
hello:
  greeting: Bonjour
  another-style-case: Upper
  style-case: upper
  position: 0  

app:
  aleatoire: ${random.int(10)}
  
---
spring:
  profiles:
  - prod
  
server:
  port: 800

logging:
  file:
    name: server.log
    path: .
  level:
    root: INFO
    org.apache.catalina: DEBUG