spring:
  jpa:
    show-sql: false

app:
  email: ${random.value}
  
appli:
  secretKey: secret
  validity: 1000
  rememberMe: 1000 

management.endpoints.web.exposure.include: info,health,metrics,mappings

  
logging:
  level:
    org.springframework.security: DEBUG  
---
spring:
  profiles:
  - prod

  datasource:
    url: jdbc:postgresql://localhost:5432/formation
    username: postgres
    password: postgres
    
    hikari:
      maximum-pool-size: 10
      connection-timeout: 5000
  jpa:
    hibernate:
      ddl-auto: update